---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-app-prod
  namespace: flux-system
spec:
  targetNamespace: prod
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./app/prod
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-app-dev
  namespace: flux-system
spec:
  targetNamespace: dev
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./app/dev
  prune: true
  wait: true
  timeout: 5m0s
